// productsData.tsx
export const products = [
  {
    id: 1,
    name: "Jersey Shorts",
    price: 19.90,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable Jersey Shorts",
    disc: "0%",
    promo: false,
  },
  {
    id: 2,
    name: "Varsity Shorts",
    price: 50.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 3,
    name: "Dri-fit Shorts",
    price: 25.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 4,
    name: "Anniversary Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 5,
    name: "Seasonal Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 6,
    name: "Jersey Tee",
    price: 19.90,
    category: "Tops",
    images: [
      "/images/products/tops/jersey_tee/FrontProfile.jpg",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 7,
    name: "Varsity Jacket",
    price: 50.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 8,
    name: "Crew-Neck Sweatshirt",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 9,
    name: "Anniversary Tee",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 10,
    name: "Anniversary Sweatshirt",
    price: 10.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 11,
    name: "V-Neck Sweatshirt",
    price: 29.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 12,
    name: "Seasonal Tees",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 13,
    name: "Fest Shirts",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 14,
    name: "Lanyard",
    price: 19.90,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 15,
    name: "Crew Socks",
    price: 50.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 16,
    name: "Long Socks",
    price: 25.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 17,
    name: "Plain Cap",
    price: 12.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: 18,
    name: "NTU Cap",
    price: 10.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "promo-seasonal-black",
    name: "Seasonal Tee - Black",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-black-1.png", "/images/seasonal-black-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black"],
    description: "Comfortable Seasonal Tee in Black",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-cap",
    name: "Cap",
    price: 10.99,
    category: "Accessories",
    images: ["/images/cap-1.png", "/images/cap-2.png"],
    stock: 15, // Adjust as needed
    sizes: ["One Size"],
    colours: ["Black", "Blue"],
    description: "Stylish cap for everyday wear",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-crewnecks-blue",
    name: "Crew Neck - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/crewnecks-blue-1.png", "/images/crewnecks-blue-2.png"],
    stock: 12, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Blue"],
    description: "Classic Blue Crew Neck",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-crewnecks-beige",
    name: "Crew Neck - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/crewnecks-beige-1.png", "/images/crewnecks-beige-2.png"],
    stock: 12, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Beige"],
    description: "Classic Beige Crew Neck",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-os-blue",
    name: "Oversized - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/os-blue-1.png", "/images/os-blue-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Blue"],
    description: "Comfortable Oversized Tee in Blue",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-os-beige",
    name: "Oversized - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/os-beige-1.png", "/images/os-beige-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Beige"],
    description: "Comfortable Oversized Tee in Beige",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-vneck-blue",
    name: "V Neck - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/vneck-blue-1.png", "/images/vneck-blue-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Blue"],
    description: "Classic V-Neck Tee in Blue",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-vneck-beige",
    name: "V Neck - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/vneck-beige-1.png", "/images/vneck-beige-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Beige"],
    description: "Classic V-Neck Tee in Beige",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-varsity",
    name: "Varsity",
    price: 10.99,
    category: "Jackets",
    images: ["/images/varsity-1.png", "/images/varsity-2.png"],
    stock: 8, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Black", "White"],
    description: "Stylish Varsity Jacket",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-seasonal-pink",
    name: "Seasonal Tee - Pink",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-pink-1.png", "/images/seasonal-pink-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Pink"],
    description: "Comfortable Seasonal Tee in Pink",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-seasonal-purple",
    name: "Seasonal Tee - Purple",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-purple-1.png", "/images/seasonal-purple-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Purple"],
    description: "Comfortable Seasonal Tee in Purple",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-socks",
    name: "Socks",
    price: 10.99,
    category: "Accessories",
    images: ["/images/socks-1.png", "/images/socks-2.png"],
    stock: 30, // Adjust as needed
    sizes: ["One Size"],
    colours: ["White", "Black"],
    description: "Comfortable socks for everyday wear",
    promo: true,
    disc: "5%",
  },
];
