// productsData.tsx
export const products = [
  {
    id: "jersey-shorts",
    name: "Jersey Shorts",
    price: 19.90,
    category: "Bottoms",
    images: ["/images/crewnecks-blue-1.png", "/images/crewnecks-blue-2.png"],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable Jersey Shorts",
    disc: "0%",
    promo: false,
  },
  {
    id: "varsity-shorts",
    name: "Varsity Shorts",
    price: 50.00,
    category: "Bottoms",
    images: ["/images/anni_shorts/annishorts.jpg",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "sports-shorts",
    name: "Sports Shorts",
    price: 25.00,
    category: "Bottoms",
    images: ["/images/drifit_shorts/drifitshorts.jpg"],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "cotton-shorts",
    name: "Cotton Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "drifit-shorts",
    name: "Dri-Fit Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "jersey-tee",
    name: "Jersey Tee",
    price: 19.90,
    category: "Tops",
    images: [
      "/images/products/tops/jersey_tee/FrontProfile.jpg",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "varsity-jacket",
    name: "Varsity Jacket",
    price: 50.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "cotton-tee",
    name: "NTU Cotton Tee",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "drifit-tee",
    name: "NTU Dri-Fit Tee",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "anniversary-sweatshirt",
    name: "Anniversary Sweatshirt",
    price: 10.00,
    category: "Tops",
    images: ["/images/anni_sweatshirt/crewnecks-blue-1.png", "/images/anni_sweatshirt/crewnecks-blue-2.png"],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "v-neck-sweatshirt",
    name: "V-Neck Sweatshirt",
    price: 29.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "seasonal-tee",
    name: "Seasonal Tees",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "fest-shirt",
    name: "Fest Shirts",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "lanyard",
    name: "Lanyard",
    price: 19.90,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["One Size"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "crew-socks",
    name: "Crew Socks",
    price: 50.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["One Size"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "long-socks",
    name: "Long Socks",
    price: 25.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["One Size"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "plain-cap",
    name: "Plain Cap",
    price: 12.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["One Size"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "ntu-cap",
    name: "NTU Cap",
    price: 10.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["One Size"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
    disc: "0%",
    promo: false,
  },
  {
    id: "promo-seasonal-black",
    name: "Seasonal Tee - Black",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-black-1.png", "/images/seasonal-black-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black"],
    description: "Comfortable Seasonal Tee in Black",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-cap",
    name: "Cap",
    price: 10.99,
    category: "Accessories",
    images: ["/images/cap-1.png", "/images/cap-2.png"],
    stock: 15, // Adjust as needed
    sizes: ["One Size"],
    colours: ["Black", "Blue"],
    description: "Stylish cap for everyday wear",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-crewnecks-blue",
    name: "Crew Neck - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/crewnecks-blue-1.png", "/images/crewnecks-blue-2.png"],
    stock: 12, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Blue"],
    description: "Classic Blue Crew Neck",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-crewnecks-beige",
    name: "Crew Neck - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/crewnecks-beige-1.png", "/images/crewnecks-beige-2.png"],
    stock: 12, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Beige"],
    description: "Classic Beige Crew Neck",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-os-blue",
    name: "Oversized - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/os-blue-1.png", "/images/os-blue-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Blue"],
    description: "Comfortable Oversized Tee in Blue",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-os-beige",
    name: "Oversized - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/os-beige-1.png", "/images/os-beige-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Beige"],
    description: "Comfortable Oversized Tee in Beige",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-vneck-blue",
    name: "V Neck - Blue",
    price: 10.99,
    category: "Tops",
    images: ["/images/vneck-blue-1.png", "/images/vneck-blue-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Blue"],
    description: "Classic V-Neck Tee in Blue",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-vneck-beige",
    name: "V Neck - Beige",
    price: 10.99,
    category: "Tops",
    images: ["/images/vneck-beige-1.png", "/images/vneck-beige-2.png"],
    stock: 10, // Adjust as needed
    sizes: ["S", "M", "L", "XL"],
    colours: ["Beige"],
    description: "Classic V-Neck Tee in Beige",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-varsity",
    name: "Varsity",
    price: 10.99,
    category: "Jackets",
    images: ["/images/varsity-1.png", "/images/varsity-2.png"],
    stock: 8, // Adjust as needed
    sizes: ["M", "L", "XL"],
    colours: ["Black", "White"],
    description: "Stylish Varsity Jacket",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-seasonal-pink",
    name: "Seasonal Tee - Pink",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-pink-1.png", "/images/seasonal-pink-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Pink"],
    description: "Comfortable Seasonal Tee in Pink",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-seasonal-purple",
    name: "Seasonal Tee - Purple",
    price: 10.99,
    category: "Tops",
    images: ["/images/seasonal-purple-1.png", "/images/seasonal-purple-2.png"],
    stock: 20, // Adjust as needed
    sizes: ["XS", "S", "M", "L"],
    colours: ["Purple"],
    description: "Comfortable Seasonal Tee in Purple",
    promo: true,
    disc: "5%",
  },
  {
    id: "promo-socks",
    name: "Socks",
    price: 10.99,
    category: "Accessories",
    images: ["/images/socks-1.png", "/images/socks-2.png"],
    stock: 30, // Adjust as needed
    sizes: ["One Size"],
    colours: ["White", "Black"],
    description: "Comfortable socks for everyday wear",
    promo: true,
    disc: "5%",
  },
];
