// productsData.tsx
export const products = [
  {
    id: 1,
    name: "Jersey Shorts",
    price: 19.90,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable Jersey Shorts",
  },
  {
    id: 2,
    name: "Varsity Shorts",
    price: 50.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 3,
    name: "Dri-fit Shorts",
    price: 25.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 4,
    name: "Anniversary Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 5,
    name: "Seasonal Shorts",
    price: 12.00,
    category: "Bottoms",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 6,
    name: "Jersey Tee",
    price: 19.90,
    category: "Tops",
    images: [
      "/images/products/tops/jersey_tee/FrontProfile.jpg",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 7,
    name: "Varsity Jacket",
    price: 50.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 8,
    name: "Crew-Neck Sweatshirt",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 9,
    name: "Anniversary Tee",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 10,
    name: "Anniversary Sweatshirt",
    price: 10.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 11,
    name: "V-Neck Sweatshirt",
    price: 29.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 12,
    name: "Seasonal Tees",
    price: 12.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 13,
    name: "Fest Shirts",
    price: 25.00,
    category: "Tops",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 14,
    name: "Lanyard",
    price: 19.90,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 15,
    name: "Crew Socks",
    price: 50.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 16,
    name: "Long Socks",
    price: 25.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 17,
    name: "Plain Cap",
    price: 12.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
  {
    id: 18,
    name: "NTU Cap",
    price: 10.00,
    category: "Accessories",
    images: ["/placeholder.svg?height=200&width=300",
    ],
    stock: 9,
    sizes: ["XS", "S", "M", "L"],
    colours: ["Black", "Red", "Navy", "Green"],
    description: "Comfortable",
  },
];
